
package Filmes;

public enum Categoria {
   UNKNOWN,ACTION,ADVENTURE,ANIMATION,CHILDREN,COMEDY,CRIME
   , DOCUMENTARY,DRAMA,FANTASY,FILMNOIR,HORROR,MUSICAL,
   MYSTERY,ROMANCE,SCIFI,THRILLER,WAR,WESTREN;
   
}
